### ISSUE TITLE
A weird error, And How to run with live speech?

### ISSUE THREAD

**Issue by corlangerak** [YuanxunLu/LiveSpeechPortraits#12]
I am wondering how to run it with realtime audio from a microphone like done in the demo video?
And is it possible to run with Pytorch CPU so without cuda?
Thanks for sharing!

**Comment by YuanxunLu** [comment]
About realtime implementation, please check section 4.4 in the paper. Specifically, I re-write the project using C++. Because some key parts of this are built based on the company's platform, it is not permitted to release these part codes for copyright-related issues.

Of course you can run the codes with CPU. Models are loaded using GPU as default. You can change the '--gpu_ids' parameters in the 'options' folder for each model.

**Comment by AK391** [comment]
@YuanxunLu also trying to run on cpu, there is no --gpu_ids in demo.py

**Comment by corlangerak** [comment]
@YuanxunLu Thanks for your reply. Would it be possible to provide some further guidance on running the python code in real-time, without violating the company's copyright?
