### ISSUE TITLE
Are there any instructions on how to train new models?

### ISSUE THREAD

**Issue by flipkast** [YuanxunLu/LiveSpeechPortraits#8]
Thanks for your amazing job~Are there any instructions on how to train new models?

**Comment by YuanxunLu** [comment]
For training procedure illustration, please check the paper sections 3 & 4.
Currently, releasing training codes is not in the plan since it involves many interests, e.g., company copyrights, closed-source tools, etc.
However, the repo has included many necessary parts, e.g., datasets/options/losses/models. This will help your implementation.
If you have more questions during the implementation, feel free to comment.
